server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: 123456@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "bG5pN2dQaXQ2R2R5N3hXa0xkZ2VqQmV6b0Nra2F0M0Q1ZlNYc1Vlb3JYUXJQdFh1WkF3ZkE="
  valid-duration: 15 # in second
  refreshable-duration: 120 # in seconds